# Generated by Django 4.2.2 on 2023-06-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reagent',
            name='alert_quantity',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
