# Generated by Django 4.2.2 on 2023-06-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0002_reagent_alert_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='labroom',
            name='room_description',
            field=models.CharField(default='Write here...', max_length=100000),
        ),
    ]
