# Generated by Django 4.2.2 on 2023-06-21 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0003_labroom_room_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='reagent',
        ),
        migrations.CreateModel(
            name='LabEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lab_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.labroom')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='lab_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lab.labequipment'),
        ),
    ]
