# Generated by Django 4.2.2 on 2023-06-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab', '0004_remove_reservation_reagent_labequipment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='quantity',
        ),
    ]
